### ISSUE TITLE
Exclude is not working ...

### ISSUE THREAD

**Issue by kkashou** [stephenmathieson/grunt-jslint#56]
This is my code structure: 

<pre>
       jslint: {
            client: {
                src: [
                    'js/**/*.js'
                ],
                exclude: [
                    'js/jsDocs/**/*.js',
                    'js/lib/**/*.js',
                    'js/scripts.min.js'
                ],
                directives: {
                    browser: true,
                    predef: [
                        'jQuery',
                        'window',
                        'document',
                        'alert'
                    ]
                }
            }
        },
</pre>

It still brings in the jsDocs and lib js files. How come?

Thanks

**Comment by smikes** [comment]
Good question!  I will look into this tomorrow morning.  Thanks for the bug report!

**Comment by kkashou** [comment]
That would be great thanks! :)

**Comment by kkashou** [comment]
Any updates on this?

**Comment by smikes** [comment]
It looks like glob expansion is not working on the excludes patterns.  I have a failing test for it now.

**Comment by smikes** [comment]
Possibly fixed.  Please try with version 1.1.13 (published to npm registry).

**Comment by kkashou** [comment]
I just tried and still ignoring the excludes patterns :/

**Comment by smikes** [comment]
Can you give me an ls -R of the directory structure

**Comment by kkashou** [comment]
Here you go.
![screen shot 2015-03-29 at 8 29 47 pm](https://cloud.githubusercontent.com/assets/8713386/6889768/673018e6-d652-11e4-858c-cad584661461.png)

**Comment by smikes** [comment]
And which files are getting linted, but shouldn't?

I was able to find a bug where the excludes were not being applied correctly, but now that is fixed, the excludes seem to be working for me.  But I am using a mock-Grunt in my tests, where I supply the list of expansions.

Can you try this:

```
src: [  'js/**/*.js', '!js/jsDocs/**/*.js', '!js/lib/**/*.js', '!js/scripts.min.js' ]
```

**Comment by kkashou** [comment]
The files that is getting linted are anything in folder js/jsDocs, js/lib and js/scripts.min.js file.

I just pulled the latest and that didn't work. I tried your latest code to and that didn't work either.

**Comment by smikes** [comment]
I mean, specifically, which files.  Is `js/scripts.min.js` getting linted?  Is `js/JsDocs/scripts/URI.js` getting linted?

**Comment by smikes** [comment]
Also I notice (now) that the directory is `js/JsDocs/` but your exclude pattern is `js/jsDocs/**/*.js`

Is your filesystem case-sensitive?

**Comment by kkashou** [comment]
That fixed it! Thanks for that catch ... sorry about that!

**Comment by smikes** [comment]
No problem!  Thanks for your persistence. There was a possibly unrelated bug in excludes, now fixed.
