### ISSUE TITLE
will it be updated?

### ISSUE THREAD

**Issue by apple77y** [stephenmathieson/grunt-jslint#58]
I used to write get, set function which is in es5 feature.
I found some articles that it covers over 1.1.0 version.
Sadly, the jslint that is in grunt-jslint is 0.8.1 version.
That's why everytime I check grunt-jslint, it faild because of these reasons.

I gotta question that is this package has possibility to update for new version?
Hope your positive feedback.

**Comment by tom--** [comment]
should probably be flagged as abandoned

**Comment by Rudloff** [comment]
Any news on this?

**Comment by Rudloff** [comment]
It seems a new release has been tagged but it's not publish on npm :/

**Comment by smikes** [comment]
@joeheyming sure, let me add you as a collaborator here and on npm

**Comment by smikes** [comment]
@joeheyming it's unfortunately a little more complicated...

1. I can add you as a project owner on npm, but not to this repo (only Stephen can do that)
2. I can publish a new version, but it won't have the latest grunt or jslint because..
3. there's some incompatibilities that need to be sorted out

**Comment by smikes** [comment]
I have published a new grunt-jslint - 1.2.0 - can you see if you can make that work?

**Comment by joeheyming** [comment]
1.1.15 is the release we want

**Comment by smikes** [comment]
Okay, I just published 1.1.15 based on 251859c3e94625c1be4af6c2d96571c441a990e1

This will be grunt-jslint@latest , but 1.2.0 will remain published too

**Comment by apple77y** [comment]
thnx guys!
